services:
  dockertest:
    image: ${DOCKER_REGISTRY-}dockertest
    build:
      context: DockerTest
      dockerfile: Dockerfile

  first_minimal_api_service:
    container_name: first_minimal_api
    image: smirnyy82/minimal-api-service:1.0
    ports:
      - "5000:8080" 
  second_minimal_api_service:
    container_name: second_minimal_api
    image: smirnyy82/minimal-api-service:1.0
    ports:
      - "6000:8080"
  third_minimal_api_service:
    container_name: third_minimal_api
    image: smirnyy82/minimal-api-service:1.0
    ports:
      - "7000:8080"
  fourth_minimal_api_service:
    container_name: fourth_minimal_api
    image: smirnyy82/minimal-api-service:1.0
    ports:
      - "8000:8080"

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "90:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - first_minimal_api_service
      - second_minimal_api_service
      - third_minimal_api_service
      - fourth_minimal_api_service

